resources:
  num_cores: 8
  numa_policy: interleave
  max_memory_mb: 8192


performance_counters: [
        "cycles", "instructions", "branches", "branch-misses",
        "cache-references", "cache-misses",
        "dTLB-loads", "dTLB-load-misses",
        "iTLB-loads", "iTLB-load-misses",
        "page-faults", "context-switches", "cpu-migrations", "task-clock"
]

benchmarks:
  - source: workloads/sparse_csr_single_thread.c
    args: ["workloads/matrices/bcsstk13.mtx"]
    runs: 5
    compiler_flags: ["-O2", "-g"]
  - source: workloads/sparse_csr.c
    args: ["workloads/matrices/bcsstk13.mtx"]
    runs: 5
    compiler_flags: ["-fopenmp", "-O2", "-g"]